install:
  infrastructure: false
frontend:
  kafka:
    url: #aws-kafka-endpoint
agenda:
  kafka:
    url: #aws-kafka-endpoint
  redis: 
    host: #aws-redis-endpoint
    # ElastiCache without auth: leave secretName unset
c4p: 
  kafka:
    url: #aws-kafka-endpoint
  postgresql:
    host: #aws-psql-endpoint
    secretName: aws-db-sql-postgres-password
    secretKey: password

notifications: 
  kafka:
    url: #aws-kafka-endpoint