apiVersion: salaboy.com/v1alpha1
kind: Environment
metadata:
  name: team-b-dev-env
  namespace: team-b
spec:
  crossplane:
    compositionSelector:
      matchLabels:
        type: development
  parameters:
    installInfra: false
