apiVersion: salaboy.com/v1alpha1
kind: Environment
metadata:
  name: team-a-dev-env
  namespace: team-a
spec:
  crossplane:
    compositionSelector:
      matchLabels:
        type: development
  parameters:
    installInfra: true
    frontend:
      debug: true
