install:
  infrastructure: false
frontend:
  kafka:
    url: my-mb-kafka-kafka-bootstrap.team-a.svc.cluster.local
agenda:
  kafka:
    url: my-mb-kafka-kafka-bootstrap.team-a.svc.cluster.local
  redis:
    host: my-db-keyvalue-redis.team-a.svc.cluster.local
    # the local keyvalue Database is a dev Valkey without auth, so no secretName
c4p:
  kafka:
    url: my-mb-kafka-kafka-bootstrap.team-a.svc.cluster.local
  postgresql:
    host: my-db-sql-postgresql-rw.team-a.svc.cluster.local
    secretName: my-db-sql-postgresql-superuser
    secretKey: password
notifications:
  kafka:
    url: my-mb-kafka-kafka-bootstrap.team-a.svc.cluster.local
